### ISSUE TITLE
Suggestion: Provide the raspberry juice emoji and ....

### ISSUE THREAD

**Issue by Ultie0** [HimbeersaftLP/MagicalHourglass#1]
Looking at your files, the emoji is required. 
But you haven't provided it. 😜

**Comment by Ultie0** [comment]
Also, the "bot?" in the whoami isn't needed because a bot can't run the command.

**Comment by HimbeersaftLP** [comment]
@Ultie0 The Bot? is for the whois command that's gonna be added in the future

**Comment by Ultie0** [comment]
oh cool

**Comment by HimbeersaftLP** [comment]
Emoji has been added to the files <3
