### ISSUE TITLE
Command handler is a mess

### ISSUE THREAD

**Issue by nathfreder** [HimbeersaftLP/MagicalHourglass#10]

**Comment by HimbeersaftLP** [comment]
> Command handler

Calling it a command handler is a slight overstatement lol

**Comment by HimbeersaftLP** [comment]
This was already a project goal for a long time btw: https://github.com/HimbeersaftLP/MagicalHourglass/projects/1#card-17260692

**Comment by HimbeersaftLP** [comment]
Fixed in version 2.0
