### ISSUE TITLE
How can i add this?

### ISSUE THREAD

**Issue by MonoAdrian23** [HimbeersaftLP/MagicalHourglass#13]
?

**Comment by HimbeersaftLP** [comment]
The ,info command has an invite.

**Comment by MonoAdrian23** [comment]
Is this a bad Joke lol

**Comment by HimbeersaftLP** [comment]
Why @MonoAdrian23? I assumed you already used my bot before (which is a reasonable assumption considering this repo is pretty obscure).

(and even if you didn't, you could have technically looked at the source code of said command to find the invite)

Anyways, here is it: https://discordapp.com/oauth2/authorize?client_id=305631536852631552&scope=bot&permissions=1144384577
