### ISSUE TITLE
Wtf ist falsch mit dir?

### ISSUE THREAD

**Issue by Buddelbubi** [HimbeersaftLP/MagicalHourglass#58]
Jemandem vom Discord kicken wegen eines Jokes? xd

**Comment by Buddelbubi** [comment]
Wo du einen ähnlichen selbst drinnen hast?? xd

**Comment by Buddelbubi** [comment]
Ich mach mich nur drüber lustig dass du mich deswegen vom Discord und vom Server bannst und dann noch behauptest ich würde mich wie ein 13 jähriger benehmen xd

**Comment by Buddelbubi** [comment]
Btw ich hab den nicht gesucht. Der is in deinem Discord Profil

**Comment by HimbeersaftLP** [comment]
Wenn es ein Profilfeld für Land gäbe, würdest du es dann auch lustig finden "Deutsches Reich" reinzuschreiben? Was du machst ist Hetze, nichts

**Comment by Buddelbubi** [comment]
Wtf. Nein. Preußen ist die einzige Wahl. xd
Fr. Deutsches Reich ist das letzte was ich reinschreiben würde.
